# Generated by Django 4.1.13 on 2025-08-01 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('control', models.CharField(blank=True, max_length=20, null=True)),
                ('editorial', models.CharField(blank=True, max_length=255, null=True)),
                ('edicion', models.CharField(blank=True, max_length=30, null=True)),
                ('publicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('catalogo', models.CharField(blank=True, max_length=500, null=True)),
                ('ebook', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LibroAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.asignatura')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.libro')),
            ],
        ),
        migrations.AddIndex(
            model_name='libro',
            index=models.Index(fields=['libro'], name='indice_libro'),
        ),
    ]
