# Generated by Django 4.1.13 on 2025-08-01 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('cod_facultad', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nom_facultad', models.CharField(blank=True, max_length=255, null=True)),
                ('icono', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='asignatura',
            old_name='nombre',
            new_name='nom_asig',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='cod_asig',
            field=models.CharField(default='SIN_CODIGO', max_length=12),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semestre',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('cod_carrera', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nom_carrera', models.CharField(blank=True, max_length=255)),
                ('grado', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.facultad')),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='cod_carrera',
            field=models.ForeignKey(default='SIN_CODIGO', on_delete=django.db.models.deletion.CASCADE, to='projects.carrera'),
            preserve_default=False,
        ),
    ]
